deploy:
  image: alpine
  stage: deploy
  dependencies:
    - build
  script:
    - apk add --no-cache lftp
    - lftp -c "set ftp:ssl-allow no; open -u deploy@empreinte-app.fr,VWtrme7Y6VXHNn ftp.dalo8522.odns.fr; mirror -R --delete dist/ /empreinte-app.fr/"
