stages:
  - deploy

deploy-recette:
  stage: deploy
  image: node:20-alpine
  script:
    - npm install
    - npm run build
    - apk add lftp
    - lftp -c "open -u $FTP_USER,$FTP_PASS ftp.dalo8522.odns.fr;mirror -R --delete dist/ /empreinte-app.fr/"
  only:
    - recette
